CREATE TABLE CAMPO (ID NUMBER(19) NOT NULL, COPERTO NUMBER(38) NULL, DATA_RIFACIMENTO DATE NULL, NOME VARCHAR2(255) NULL, STATO VARCHAR2(255) NULL, TIPO VARCHAR2(255) NULL, PRIMARY KEY (ID))
CREATE SEQUENCE CAMPO_SEQ INCREMENT BY 50 START WITH 50
